#ifndef VERSION_H
#define VERSION_H

#define A_PLUS_PLUS_VERSION_MAJOR 0
#define A_PLUS_PLUS_VERSION_MINOR 4
#define A_PLUS_PLUS_VERSION_PATCH 1
#define A_PLUS_PLUS_VERSION_STRING "0.4.1"

#endif // VERSION_H
