#ifndef VERSION_H
#define VERSION_H

#define A_PLUS_PLUS_VERSION_MAJOR 0
#define A_PLUS_PLUS_VERSION_MINOR 5
#define A_PLUS_PLUS_VERSION_PATCH 0
#define A_PLUS_PLUS_VERSION_STRING "0.5.0"

#endif // VERSION_H
